config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists, only: [:show, :new, :create, :edit, :update, :destroy ] do
    resources :bookmarks, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_one_attached :photo
  has_many :movies, through: :bookmarks
  validates :name, presence: { message: "must be given please" }, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :get_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = Bookmark.find(params[:id]).list
    Bookmark.delete(params[:id])
    redirect_to list_path(@list)
  end
  private
  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def get_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  def index
    @lists = List.all
    @picture = 'https://i.pinimg.com/236x/84/1f/50/841f507da4e560ddb2743010e08f668f--cool-hand-luke-lemony-snicket.jpg';
  end
  def show
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  def edit
  end

  def update
    @list.update(list_params)
    if @list.valid?
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment%>
  <%= f.association :movie, collection: Movie.all, input_html: { class: 'multiselectuser'} %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name%>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="add-bottom-padding" style="background-image: radial-gradient(#241f31 1%, black 95%);">
  <div class="w-100 p-2 d-flex justify-content-end bg-black sticky-top">
    <%= link_to "Create List", new_list_path, class: "btn btn-info m-1 fw-bold lh-lg mx-2" %>
    <%= link_to "My List", root_path, class: "btn btn-info m-1 fw-bold lh-lg mx-4" %>

  </div>
  <div class="main-banner rounded" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.3)), url(https://cdn.dribbble.com/userupload/12254505/file/original-8012c0bcfac68053bbd9f87b26278da1.png?resize=752x)">
    <h1 class="home-header">movies lists</h1>
  </div>

  <%if @lists.length == 0 %>
    <div class="text-center text-light p-5 d-flex justify-content-center align-items-center flex-column" style="height:%">
        <div>
          <h2>You dont have a list yet!<h2>
        </div>
        <div class="add-div d-flex justify-content-center align-items-center bg-dark rounded" style="">
          <%= link_to new_list_path do %>
          <i class="show-icon fa-solid fa-plus icon-settings text-white"></i>
          <%end %>
          <i class="show-add icon-settings text-white"></i>
        </div>
    </div>

  <%else%>
    <div class="p-5 d-flex flex-wrap justify-content-center" style="height:100%">
        <% @lists.each do |list|%>
          <%= link_to list_path(list) do%>
            <div class="card-list m-5">
              <div class="pic-div d-flex justify-content-center align-items-center bg-dark">
                <% if list.photo.key.nil? %>
                  <i class="fa-solid fa-play icon-settings text-white"></i>
                <% else %>
                  <%= cl_image_tag list.photo.key, class:"image-fit"%>
                <% end %>
              </div>
              <%= link_to "", list_path(list), class:"card-delete-list fa-solid fa-trash text-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <div class="card-list-infos bg-black">
                <div class="text-white">
                  <h2><%=list.name%></h2>
                </div>
                <%= link_to :edit, edit_list_path(list), class:"btn btn-primary"%>
              </div>
            </div>
          <% end %>
        <%end%>
    </div>
  <%end%>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name%>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="" >
  <div class="w-100 p-1 d-flex justify-content-between shadow-lg fixed-top bg-black">
    <%= link_to "Add Movies", new_list_bookmark_path(@list), class: "btn btn-info m-1 fw-bold lh-lg"%>
    <div>
      <%= link_to "My List", root_path, class: "btn btn-info m-1 fw-bold lh-lg" %>
      <%= link_to "Create List", new_list_path, class: "btn btn-info m-1 fw-bold lh-lg" %>
    </div>
  </div>
  <div class="w-100 bg-secondary fit-image" style="background-image: url('https://w.wallhaven.cc/full/83/wallhaven-83kvv1.jpg'); height:65vh">
  </div>
  <div style="height:100%; background-image: radial-gradient(circle ,#241f31 1%, black 95%);">
  <div class="py-5"><h1 class="text-center show-header"><%= @list.name%></h1></div>
    <div class="d-flex justify-content-evenly flex-wrap p-5">
      <%if @bookmarks.length == 0%>
        <div class="text-center text-light p-5 d-flex justify-content-center align-items-center flex-column" style="height:%">
        <div>
          <h2>Add a bookmark<h2>
        </div>
        <div class="add-div d-flex justify-content-center align-items-center bg-dark rounded" style="">
          <%= link_to new_list_bookmark_path(@list) do %>
          <i class="show-icon fa-solid fa-plus icon-settings text-white"></i>
          <%end %>
          <i class="show-add icon-settings text-white"></i>
        </div>
        </div>
      <%else%>
        <%@bookmarks.each do |bookmark|%>
          <div class="card bg-light m-3" style="width: 25rem;">
            <%= image_tag bookmark.movie.poster_url, class:"card-img-top"%>
            <div class="card-body">
              <p class="card-text"><%=bookmark.movie.overview%></p>
            </div>
            <div class="d-flex justify-content-between border bg-light p-2">
              <span class="px-4 fst-italic comment-spacing">-<%=bookmark.comment%></span>
              <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash text-gray"></i>
              <%end%>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>
  </div>
</div>